name: Version Check

on:
  pull_request:
    branches:
      - main 

jobs:
  version-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt 

    - name: Install nanometa
      run: |
        pip install .

    - name: Check nanometa-sim version
      run: nanometa-sim --version  

    - name: Check nanometa-new version
      run: nanometa-new --version 

    - name: Check nanometa-pipe version
      run: nanometa-pipe --version 
